In [1]:
print(1)

1

In [2]:
print('the weather is well')

the weather is well

In [3]:
print(1+3)

4

In [4]:
print('1'+'3')

13

In [5]:
import pandas
pandas.read_csv

<function pandas.io.parsers._make_parser_function.<locals>.parser_f(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)>

In [6]:
import pandas

In [38]:
pandas.read_csv('C:\\Users\\EELab507\\Desktop\\20180719\\newimm_d .CSV',encoding='ANSI')

,臺北市新移民統計,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,序\n號,統計項目,NaN,填報\n機關,單位,統計項目定義,公式,資料產生週期,資料產生時間,資料,...,NaN,NaN,NaN,NaN,107年1-3月(底)較上年同期增減百分點,資料差異原因,改進措施,備註,確認紀錄,對應「臺北市新移民照顧輔導政策及實施方案執行情形統計」之項目序號
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94年(底),...,106年1-9月(底),106年(底),106年1-3月(底),107年1-3月(底),NaN,NaN,NaN,NaN,NaN,NaN
2,1,新移民人口結構比率,NaN,民政局,%,在臺北市各地區新移民人口結構比率,(全市新移民人口數/全市新移民人口數)×100,月,當期期末,"100.00\n(27,645人)",...,"100.00\n(34,853人)","100.00\n(35,063人)","100.00\n(34,587人)","100.00\n(35,244人)",NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,大陸港澳配偶比率,民政局,%,大陸港澳配偶人數占全市新移民人口數之比率,(大陸港澳配偶人數/全市新移民人口數)×100,月,當期期末,90.1,...,89.05,89.01,89.1,88.96,-0.14,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,其他外籍配偶比率,民政局,%,其他外籍配偶人數占全市新移民人口數之比率,(其他外籍配偶人數/全市新移民人口數)×100,月,當期期末,9.9,...,10.95,10.99,10.9,11.04,0.14,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,越南籍配偶,民政局,%,越南籍配偶人數占全市新移民人口數之比率,(越南籍配偶人數/全市新移民人口數)×100,月,當期期末,4.51,...,2.67,2.67,2.68,2.67,-0.01,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,日本籍配偶,民政局,%,日本籍配偶人數占全市新移民人口數之比率,(日本籍配偶人數/全市新移民人口數)×100,月,當期期末,NaN,...,1.69,1.68,1.68,1.7,0.02,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,美國籍配偶,民政局,%,美國籍配偶人數占全市新移民人口數之比率,(美國籍配偶人數/全市新移民人口數)×100,月,當期期末,NaN,...,1.37,1.38,1.36,1.4,0.04,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,印尼籍配偶,民政局,%,印尼籍配偶人數占全市新移民人口數之比率,(印尼籍配偶人數/全市新移民人口數)×100,月,當期期末,1.44,...,0.6,0.6,0.6,0.6,0,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,韓國籍配偶,民政局,%,韓國籍配偶人數占全市新移民人口數之比率,(韓國籍配偶人數/全市新移民人口數)×100,月,當期期末,NaN,...,0.47,0.48,0.47,0.48,0.01,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,加拿大籍配偶,民政局,%,加拿大籍配偶人數占全市新移民人口數之比率,(加拿大籍配偶人數/全市新移民人口數)×100,月,當期期末,NaN,...,0.36,0.37,0.37,0.37,0,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,泰國籍配偶,民政局,%,泰國籍配偶人數占全市新移民人口數之比率,(泰國籍配偶人數/全市新移民人口數)×100,月,當期期末,0.62,...,0.37,0.39,0.36,0.39,0.03,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,新加坡籍配偶,民政局,%,新加坡籍配偶人數占全市新移民人口數之比率,(新加坡籍配偶人數/全市新移民人口數)×100,月,當期期末,NaN,...,0.28,0.28,0.28,0.28,0,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,菲律賓籍配偶,民政局,%,菲律賓籍配偶人數占全市新移民人口數之比率,(菲律賓籍配偶人數/全市新移民人口數)×100,月,當期期末,0.39,...,0.26,0.27,0.27,0.27,0,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,緬甸籍配偶,民政局,%,緬甸籍配偶人數占全市新移民人口數之比率,(緬甸籍配偶人數/全市新移民人口數)×100,月,當期期末,…,...,0.19,0.19,0.19,0.18,-0.01,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,其他籍配偶,民政局,%,其他籍配偶人數占全市新移民人口數之比率,(其他籍配偶人數/全市新移民人口數)×100,月,當期期末,2.68,...,2.68,2.7,2.65,2.69,0.04,NaN,NaN,其他國籍係指法國、澳大利亞、德國、荷蘭、巴西、土耳其、尼泊爾王國、波蘭、俄羅斯、哥倫比亞與義...,NaN,NaN
16,2,新移民人口性比例,NaN,民政局,男/百女,新移民男性人口對女性人口的比例，即每百女子相對男子數。,(新移民男性人口數÷新移民女性人口數)×100,月,當期期末,NaN,...,11.48,11.59,11.48,11.71,0.23,NaN,NaN,NaN,NaN,NaN
17,3,新移民人口比率,NaN,民政局,%,新移民人口數占全市人口百分比,(新移民人口數/全市人口數)×100,月,當期期末,1.06,...,1.3,1.31,1.28,1.31,0.03,NaN,NaN,NaN,NaN,NaN
18,4,新移民人口年齡結構比率,NaN,民政局,%,本市新移民人口年齡結構比率,(全市新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,"100.00\n(34,853人)","100.00\n(35,063人)","100.00\n(34,587人)","100.00\n(35,244人)",NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,0至未滿6歲,民政局,%,0至未滿6歲新移民人口數占全市新移民人口數之比率,(全市0至未滿6歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0,0,0,0,0,NaN,NaN,資料來源係內政部戶政司戶役政系統，數據統計以本國籍配偶設籍於本市之新移民人數，出現18歲以下...,NaN,NaN
20,NaN,NaN,6至未滿12歲,民政局,%,6至未滿12歲新移民人口數占全市新移民人口數之比率,(全市6至未滿12歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0,0,0.01,0,-0.01,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,12至未滿15歲,民政局,%,12至未滿15歲新移民人口數占全市新移民人口數之比率,(全市12至未滿15歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0.01,0,0.01,0,-0.01,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,15至未滿18歲,民政局,%,15至未滿18歲新移民人口數占全市新移民人口數之比率,(全市15至未滿18歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0.01,0.01,0.01,0.01,0,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,18至未滿24歲,民政局,%,18至未滿24歲新移民人口數占全市新移民人口數之比率,(全市18至未滿24歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0.84,0.26,0.76,0.22,-0.54,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,24至未滿30歲,民政局,%,24至未滿30歲新移民人口數占全市新移民人口數之比率,(全市24至未滿30歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,10.73,5.92,10.37,5.59,-4.78,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,30至未滿45歲,民政局,%,30至未滿45歲新移民人口數占全市新移民人口數之比率,(全市30至未滿45歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,56.12,54.32,56.31,53.98,-2.33,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,45至未滿65歲,民政局,%,45至未滿65歲新移民人口數占全市新移民人口數之比率,(全市45至未滿65歲新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,28.64,34.67,28.86,35.21,6.35,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,65歲以上,民政局,%,65歲以上新移民人口數占全市新移民人口數之比率,(全市65歲以上新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,3.64,4.81,3.67,4.99,1.32,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,年齡不詳,民政局,%,年齡不詳新移民人口數占全市新移民人口數之比率,(全市年齡不詳新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,0.01,0.01,0.01,0.01,0,NaN,NaN,NaN,NaN,NaN
29,5,新移民人口年齡結構比率按國籍別分,NaN,民政局,%,本市新移民人口年齡結構比率,(全市新移民人口數/全市新移民人口數)×100,月,當期期末,NaN,...,"100.00\n(34,853人)","100.00\n(35,063人)","100.00\n(34,587人)","100.00\n(35,244人)",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,NaN,NaN,參加就業研習班人次比率,勞動局\n,%,新移民參加就業研習班及團體就業研習班人次占新移民參加各類課程總人次比率,(新移民參加就業研習班及團體就業研習班人次/新移民參加各類課程總人次)×100,季,當期,26.13,...,21.73,25.58,…,…,- -,NaN,NaN,107年1-3月:\n100人次,NaN,二、一、6及7
70,11,新移民取得駕照人數占新移民人數比率,NaN,臺北\n市區\n監理所,%,新移民取得汽車駕照人數占新移民人數之比率,(新移民取得汽車駕照人數/期中新移民人數)×100,季,當期,1.11,...,0.97,1.25,0.32,0.22,-0.1,NaN,NaN,NaN,NaN,一、五、3\n
71,12,考駕照及格率,NaN,臺北\n市區\n監理所,%,新移民考取駕照人次占新移民參加駕照考試人次之比率,(新移民取得汽車或機車駕照人次/新移民參加駕照考試人次)×100,季,當期,…,...,63.61,64.18,58.24,63.06,4.82,NaN,NaN,NaN,NaN,一、五、2及3\n
72,13,各項諮詢服務人次結構比率,NaN,NaN,%,新移民各項諮詢服務人次結構比率,(新移民各項諮詢服務人次/新移民各項諮詢服務總人次)×100\n新移民各項諮詢服務總人次=新...,季,當期,"100.00\n(3,272人次)",...,"100.00\n(7,306人次)","100.00\n(9,740人次)","100.00\n(1,983人次)","100.00\n(1,795人次)",NaN,NaN,NaN,NaN,NaN,一、六及七
73,NaN,NaN,新移民會館電話諮詢服務人次比率,民政局\n,%,新移民會館電話諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民會館電話諮詢服務人次/新移民各項諮詢服務總人次)×100,月,當期,2.96,...,30.19,28.62,38.43,33.98,-4.45,NaN,NaN,107年1-3月:\n610人次,NaN,一、六、1
74,NaN,NaN,課程諮詢及申訴專線服務人次比率,教育局\n,%,新移民課程諮詢及申訴專線服務人次占新移民各項諮詢服務總人次之比率,(新移民課程諮詢及申訴專線服務人次/新移民各項諮詢服務總人次)×100,季,當期,-,...,0.11,0.3,0.35,0.61,0.26,NaN,NaN,107年1-3月:\n11人次,NaN,一、六、6
75,NaN,NaN,職業訓練電話諮詢服務人次比率,勞動局\n,%,新移民職業訓練電話諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民職業訓練電話諮詢服務人次/新移民各項諮詢服務總人次)×100,季,當期,…,...,1.04,1.02,1.06,1.11,0.05,NaN,NaN,107年1-3月:\n20人次,NaN,一、六、7
76,NaN,NaN,就業服務電話諮詢服務人次比率,勞動局\n,%,新移民就業服務電話諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民就業服務電話諮詢服務人次/新移民各項諮詢服務總人次)×100,季,當期,…,...,10.05,9.7,9.98,10.92,0.94,NaN,NaN,107年1-3月:\n196人次,NaN,一、六、8 \n
77,NaN,NaN,健康諮詢站諮詢服務人次,衛生局,%,新移民健康諮詢站諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民健康諮詢站諮詢服務人次/新移民各項諮詢服務總人次)×100,季,當期,NaN,...,41.55,44.36,30.21,34.04,3.83,NaN,NaN,107年1-3月:\n611人次,NaN,一、六、9 \n
78,NaN,NaN,新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次比率,社會局,%,新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次/新移民各項諮詢服務總人次)×100,季,當期,86.77,...,14.3,13.15,14.62,17.33,2.71,NaN,NaN,107年1-3月:\n311人次,NaN,一、六、16
79,NaN,NaN,法律諮詢服務人次比率,秘書處,%,新移民法律諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民法律諮詢服務人次/新移民各項諮詢服務總人次)×100,月,當期,1.01,...,0.83,0.75,1.61,1,-0.61,NaN,NaN,107年1-3月:\n18人次,NaN,一、七、1
80,NaN,NaN,婦女暨家庭服務中心及家暴中心提供法律諮詢服務人次比率,社會局,%,新移民婦女暨家庭服務中心及家暴中心提供新移民法律諮詢服務人次占新移民各項諮詢服務總人次之比率,(新移民婦女暨家庭服務中心及家暴中心提供法律諮詢服務人次/新移民各項諮詢服務總人次)×100,季,當期,9.26,...,1.92,2.09,3.73,1,-2.73,NaN,NaN,107年1-3月:\n18人次,NaN,一、七、2
81,14,求職就業率,NaN,勞動局,%,新移民求職推介就業人數占新移民登記求職人數之比率,(有效求職推介新移民就業人數/新移民登記求職人數)×100,月,當期,56.46,...,30.85,30.78,28.26,30.95,2.69,NaN,NaN,NaN,NaN,二、一、1及2
82,15,參加就業研習人次占全市比率,NaN,勞動局,%,新移民參加就業研習班及團體就業研習班人次占全市參加就業研習人次之比率,(新移民參加就業研習班及團體就業研習班人次/全市參加就業研習人次)×100,季,當期,12.14,...,3.91,3.9,4.44,4.51,0.07,NaN,NaN,NaN,NaN,二、一、6及7
83,16,參加職訓人次比率,NaN,勞動局,%,新移民參加職訓人次占全市參加職訓人次之比率,(新移民參加職訓人次/全市參加職訓人次)×100,季,當期,3.91,...,1.93,1.64,0.64,0.89,0.25,NaN,NaN,NaN,NaN,二、二、2
84,17,新婚個案訪視個案完訪率,NaN,衛生局,%,新移民新婚個案已完訪案數占新婚新移民應建卡案數之比率，其中新婚新移民應建卡案數係指新婚新移民...,(新移民新婚個案已完訪案數/新婚新移民應建卡案數)×100,季,當期,100,...,100,100,100,100,0,NaN,NaN,NaN,NaN,三、一、1及2
85,18,子女訪視個案完訪率,NaN,衛生局,%,新移民子女收案訪視個案已完訪案數占新移民子女應建卡案數之比率，其中新移民子女應建卡案數係指扣...,(新移民子女收案訪視個案已完訪案數/新移民子女應建卡案數)×100,季,當期,100,...,100,100,100,100,0,NaN,NaN,NaN,NaN,三、一、3及4
86,19,提供新移民懷孕婦女產前衛教諮詢服務個案率,NaN,衛生局,%,新移民懷孕婦女個案數占提供新移民懷孕婦女產前衛教諮詢服務個案數之比率,(提供新移民懷孕婦女產前衛教諮詢服務個案數/新移民懷孕婦女個案數)×100,季,當期,100,...,100,100,100,100,0,NaN,NaN,NaN,NaN,三、一、7及8
87,20,各類緊急救援、庇護安置及輔導服務人次比率,NaN,社會局,%,家暴防治中心受理新移民家暴及性侵害案件中，進行緊急救援、庇護安置及心理諮商輔導人次占家暴防治...,(新移民接受緊急救援、庇護安置及心理諮商輔導人次/全市接受緊急救援、庇護安置及心理諮商輔導人...,季,當期,5.95,...,3.74,2.06,4.02,4.29,0.27,NaN,NaN,NaN,NaN,四、一、1
88,21,辦理新移民多元文化週活動國小學校比率,NaN,教育局,%,辦理新移民多元文化週活動國小學校占全市國小學校校數之比率,(辦理新移民多元文化週活動國小學校校數/全市國小學校校數)×100,學年度,當期,100,...,…,100,…,…,- -,NaN,NaN,該資料為每學年統計一次，各年資料係指各學年度資料。,NaN,五、三、10
89,22,遭逢特殊境遇家庭經濟支持服務人次比率,NaN,社會局,%,提供遭逢特殊境遇新移民家庭各項經濟支持服務人次占全市提供遭逢特殊境遇家庭各項經濟支持服務人次之比率,(提供遭逢特殊境遇新移民家庭各項經濟支持服務人次/全市提供遭逢特殊境遇家庭各項經濟支持服務人...,季,當期,1.21,...,1.42,1.44,1.59,1.8,0.21,NaN,NaN,NaN,NaN,六、四、5
90,23,國小新移民學生比率,NaN,教育局,%,就讀國小之新移民子女人數占全市國小學生數比率,(就讀國小之新移民子女人數/全市國小學生數)×100,學年度,當期,2.69,...,…,7.16,…,…,- -,NaN,NaN,該資料為每學年統計一次，各年資料係指各學年度資料。,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,(新移民學生數:人),"(新移民學生數:8,340人)",(新移民學生數:\n人),(新移民學生數:人),NaN,NaN,NaN,NaN,NaN,NaN
92,24,國中新移民學生比率,NaN,教育局,%,就讀公私立國中之新移民子女人數占全市公私立國中學生數比率,(就讀公私立國中之新移民子女人數/全市公私立國中學生數)×100,學年度,當期,1.09,...,…,7.14,…,…,- -,NaN,NaN,該資料為每學年統計一次，各年資料係指各學年度資料。,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,(新移民學生數:人),"(新移民學生數:4,763人)",(新移民學生數:\n人),(新移民學生數:人),NaN,NaN,NaN,NaN,NaN,NaN
94,25,子女優先進入公立幼兒園人數占全市比率,NaN,教育局,%,3至未滿6歲新移民子女優先進入公立幼兒園人數占全市公立幼兒園人數之比率,(新移民3至未滿6歲子女優先進入公立幼兒園人數/公立幼兒園核定人數)×100,學年度,當期,2.91,...,…,0.57,…,…,- -,NaN,NaN,該資料為每學年統計一次，各年資料係指各學年度資料。,NaN,八、二、3\n
95,26,子女完成兒童發展篩檢表比率\n\n,NaN,衛生局,%,0-3歲完成兒童發展篩檢表之新移民子女人數占本市0-3歲新移民子女人數比率,(0-3歲完成兒童發展篩檢表之新移民子女人數/全市0-3歲新移民子女人數)×100,季,當期,…,...,72.13,92.51,1.84,2.26,0.42,NaN,NaN,NaN,NaN,八、二、4\n
96,27,子女早期療育服務人數占全市比率,NaN,社會局,%,提供新移民子女發展遲緩者早期療育服務人數占全市提供發展遲緩者早期療育服務人數之比率,(提供新移民子女發展遲緩者早期療育服務人數/全市提供發展遲緩者早期療育服務人數)×100,季,當期,3.94,...,5.21,6.01,4.21,4.68,0.47,NaN,NaN,本案未扣除戶籍遷至外縣市、未實際居住本市、死亡、拒訪。,(491/5513)×100 (累計至103年止0至6歲新移民子女通報在案總數/累計至...,八、二、5、6
97,28,身心障礙子女幼兒教育補助人數比率,NaN,教育局,%,就讀私立幼兒園之2至6歲身心障礙幼兒且其父母一方為新移民者教育補助人數占全市私立幼兒園之2至...,(新移民就讀私立幼兒園之2至6歲身心障礙幼兒教育補助人數/全市私立幼兒園之2至6歲身心障礙幼...,學年度,當期,3.02,...,…,3.23,…,…,- -,NaN,NaN,1.該資料為每學年統計一次，各年資料係指各學年度資料。\n2.本案需經本市特殊教育學生鑑定及...,NaN,八、二、9\n
98,29,國小子女學校課後輔導人次比率,NaN,教育局,%,本市國民小學依教育部「國民小學辦理兒童課後照顧服務人員及資格標準修正條文」及「臺北市國民小學...,(新移民國小兒童課後輔導人次/全市國小兒童課後輔導人次)×100,學年度,當期,0.28,...,…,18.66,…,…,- -,NaN,NaN,該資料為每學年統計一次，各年資料係指各學年度資料。,NaN,八、二、2

In [40]:
import pandas
pandas.read_csv('C:\\Users\\EELab507\\Desktop\\20180719\\taipeifireworkpot.csv,encoding='BIG5')

SyntaxError: invalid syntax (<ipython-input-40-425451e353ed>, line 2)

In [42]:
import pandas
pandas.read_csv('C:\\Users\\EELab507\\Desktop\\20180719\\taipeifireworkpot.csv,encoding='ANSI')

SyntaxError: invalid syntax (<ipython-input-42-f9d2e22b7371>, line 2)

In [43]:
import pandas as pd
df=pd.read_csv('taipeifireworkpot.csv',encoding='big5')
print(df)

     分隊名稱     X97      Y97
0    古亭分隊  304296  2767192
1    華山分隊  302552  2771114
2    忠孝分隊  303184  2770719
3    泉州分隊  301717  2768601
4    城中分隊  301807  2771076
5    雙園分隊  300004  2769060
6    龍山分隊  300137  2770145
7    萬芳分隊  307177  2766126
8    景美分隊  304631  2765034
9    木柵分隊  306876  2764656
10   寶橋分隊  306021  2763666
11   金華分隊  303258  2769481
12   安和分隊  305731  2769536
13   復興分隊  304827  2769217
14   南港分隊  311271  2771970
15   舊莊分隊  312085  2770911
16   信義分隊  307391  2770418
17   永吉分隊  307433  2770941
18   莊敬分隊  307040  2769197
19   成德分隊  309230  2771216
20   大直分隊  306136  2774777
21   松江分隊  303875  2771146
22   圓山分隊  303386  2773471
23   八德分隊  306804  2771272
24   中崙分隊  305076  2771247
25   東湖分隊  311835  2773391
26   大湖分隊  310690  2775204
27   內湖分隊  309559  2773607
28   民權分隊  308283  2773311
29   建國分隊  304063  2773398
30   建成分隊  302289  2771942
31   延平分隊  301597  2771439
32   大同分隊  301831  2772685
33  山仔后分隊  305021  2780715
34   天母分隊  303737  2779758
35   福安分隊  300166  2776454
36   社子分隊  301597  2774636
37   劍潭分隊  303168  2775854
38   雙溪分隊  304937  2776701
39  陽明山分隊  305111  2782678
40   光明分隊  300664  2780842
41   關渡分隊  297059  2779489
42   石牌分隊  302127  2778941
43   秀山分隊  299695  2781960
44   後港分隊  302255  2775551

In [45]:
import pandas as pd
df=pd.read_csv('newimm_d .CSV',encoding='ANSI')
print(df)

   臺北市新移民統計            Unnamed: 1                    Unnamed: 2   Unnamed: 3  \
0      序\n號                  統計項目                           NaN       填報\n機關
1       NaN                   NaN                           NaN          NaN
2         1             新移民人口結構比率                           NaN          民政局
3       NaN                   NaN                      大陸港澳配偶比率          民政局
4       NaN                   NaN                      其他外籍配偶比率          民政局
5       NaN                   NaN                         越南籍配偶          民政局
6       NaN                   NaN                         日本籍配偶          民政局
7       NaN                   NaN                         美國籍配偶          民政局
8       NaN                   NaN                         印尼籍配偶          民政局
9       NaN                   NaN                         韓國籍配偶          民政局
10      NaN                   NaN                        加拿大籍配偶          民政局
11      NaN                   NaN                         泰國籍配偶          民政局
12      NaN                   NaN                        新加坡籍配偶          民政局
13      NaN                   NaN                        菲律賓籍配偶          民政局
14      NaN                   NaN                         緬甸籍配偶          民政局
15      NaN                   NaN                         其他籍配偶          民政局
16        2              新移民人口性比例                           NaN          民政局
17        3               新移民人口比率                           NaN          民政局
18        4           新移民人口年齡結構比率                           NaN          民政局
19      NaN                   NaN                        0至未滿6歲          民政局
20      NaN                   NaN                       6至未滿12歲          民政局
21      NaN                   NaN                      12至未滿15歲          民政局
22      NaN                   NaN                      15至未滿18歲          民政局
23      NaN                   NaN                      18至未滿24歲          民政局
24      NaN                   NaN                      24至未滿30歲          民政局
25      NaN                   NaN                      30至未滿45歲          民政局
26      NaN                   NaN                      45至未滿65歲          民政局
27      NaN                   NaN                         65歲以上          民政局
28      NaN                   NaN                          年齡不詳          民政局
29        5      新移民人口年齡結構比率按國籍別分                           NaN          民政局
..      ...                   ...                           ...          ...
69      NaN                   NaN                   參加就業研習班人次比率        勞動局\n
70       11     新移民取得駕照人數占新移民人數比率                           NaN  臺北\n市區\n監理所
71       12                考駕照及格率                           NaN  臺北\n市區\n監理所
72       13          各項諮詢服務人次結構比率                           NaN          NaN
73      NaN                   NaN               新移民會館電話諮詢服務人次比率        民政局\n
74      NaN                   NaN               課程諮詢及申訴專線服務人次比率        教育局\n
75      NaN                   NaN                職業訓練電話諮詢服務人次比率        勞動局\n
76      NaN                   NaN                就業服務電話諮詢服務人次比率        勞動局\n
77      NaN                   NaN                   健康諮詢站諮詢服務人次          衛生局
78      NaN                   NaN  新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次比率          社會局
79      NaN                   NaN                    法律諮詢服務人次比率          秘書處
80      NaN                   NaN    婦女暨家庭服務中心及家暴中心提供法律諮詢服務人次比率          社會局
81       14                 求職就業率                           NaN          勞動局
82       15         參加就業研習人次占全市比率                           NaN          勞動局
83       16              參加職訓人次比率                           NaN          勞動局
84       17           新婚個案訪視個案完訪率                           NaN          衛生局
85       18             子女訪視個案完訪率                           NaN          衛生局
86       19  提供新移民懷孕婦女產前衛教諮詢服務個案率                           NaN          衛生局
87       20  各類緊急救援、庇護安置及輔導服務人次比率                           NaN          社會局
88       21    辦理新移民多元文化週活動國小學校比率                           NaN          教育局
89       22    遭逢特殊境遇家庭經濟支持服務人次比率                           NaN          社會局
90       23             國小新移民學生比率                           NaN          教育局
91      NaN                   NaN                           NaN          NaN
92       24             國中新移民學生比率                           NaN          教育局
93      NaN                   NaN                           NaN          NaN
94       25    子女優先進入公立幼兒園人數占全市比率                           NaN          教育局
95       26     子女完成兒童發展篩檢表比率\n\n                           NaN          衛生局
96       27       子女早期療育服務人數占全市比率                           NaN          社會局
97       28      身心障礙子女幼兒教育補助人數比率                           NaN          教育局
98       29        國小子女學校課後輔導人次比率                           NaN          教育局

   Unnamed: 4                                         Unnamed: 5  \
0          單位                                             統計項目定義
1         NaN                                                NaN
2           %                                   在臺北市各地區新移民人口結構比率
3           %                               大陸港澳配偶人數占全市新移民人口數之比率
4           %                               其他外籍配偶人數占全市新移民人口數之比率
5           %                                越南籍配偶人數占全市新移民人口數之比率
6           %                                日本籍配偶人數占全市新移民人口數之比率
7           %                                美國籍配偶人數占全市新移民人口數之比率
8           %                                印尼籍配偶人數占全市新移民人口數之比率
9           %                                韓國籍配偶人數占全市新移民人口數之比率
10          %                               加拿大籍配偶人數占全市新移民人口數之比率
11          %                                泰國籍配偶人數占全市新移民人口數之比率
12          %                               新加坡籍配偶人數占全市新移民人口數之比率
13          %                               菲律賓籍配偶人數占全市新移民人口數之比率
14          %                                緬甸籍配偶人數占全市新移民人口數之比率
15          %                                其他籍配偶人數占全市新移民人口數之比率
16       男/百女                        新移民男性人口對女性人口的比例，即每百女子相對男子數。
17          %                                     新移民人口數占全市人口百分比
18          %                                      本市新移民人口年齡結構比率
19          %                           0至未滿6歲新移民人口數占全市新移民人口數之比率
20          %                          6至未滿12歲新移民人口數占全市新移民人口數之比率
21          %                         12至未滿15歲新移民人口數占全市新移民人口數之比率
22          %                         15至未滿18歲新移民人口數占全市新移民人口數之比率
23          %                         18至未滿24歲新移民人口數占全市新移民人口數之比率
24          %                         24至未滿30歲新移民人口數占全市新移民人口數之比率
25          %                         30至未滿45歲新移民人口數占全市新移民人口數之比率
26          %                         45至未滿65歲新移民人口數占全市新移民人口數之比率
27          %                            65歲以上新移民人口數占全市新移民人口數之比率
28          %                             年齡不詳新移民人口數占全市新移民人口數之比率
29          %                                      本市新移民人口年齡結構比率
..        ...                                                ...
69          %                新移民參加就業研習班及團體就業研習班人次占新移民參加各類課程總人次比率
70          %                               新移民取得汽車駕照人數占新移民人數之比率
71          %                           新移民考取駕照人次占新移民參加駕照考試人次之比率
72          %                                    新移民各項諮詢服務人次結構比率
73          %                      新移民會館電話諮詢服務人次占新移民各項諮詢服務總人次之比率
74          %                   新移民課程諮詢及申訴專線服務人次占新移民各項諮詢服務總人次之比率
75          %                    新移民職業訓練電話諮詢服務人次占新移民各項諮詢服務總人次之比率
76          %                    新移民就業服務電話諮詢服務人次占新移民各項諮詢服務總人次之比率
77          %                     新移民健康諮詢站諮詢服務人次占新移民各項諮詢服務總人次之比率
78          %         新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次占新移民各項諮詢服務總人次之比率
79          %                        新移民法律諮詢服務人次占新移民各項諮詢服務總人次之比率
80          %     新移民婦女暨家庭服務中心及家暴中心提供新移民法律諮詢服務人次占新移民各項諮詢服務總人次之比率
81          %                           新移民求職推介就業人數占新移民登記求職人數之比率
82          %                 新移民參加就業研習班及團體就業研習班人次占全市參加就業研習人次之比率
83          %                              新移民參加職訓人次占全市參加職訓人次之比率
84          %  新移民新婚個案已完訪案數占新婚新移民應建卡案數之比率，其中新婚新移民應建卡案數係指新婚新移民...
85          %  新移民子女收案訪視個案已完訪案數占新移民子女應建卡案數之比率，其中新移民子女應建卡案數係指扣...
86          %                 新移民懷孕婦女個案數占提供新移民懷孕婦女產前衛教諮詢服務個案數之比率
87          %  家暴防治中心受理新移民家暴及性侵害案件中，進行緊急救援、庇護安置及心理諮商輔導人次占家暴防治...
88          %                       辦理新移民多元文化週活動國小學校占全市國小學校校數之比率
89          %  提供遭逢特殊境遇新移民家庭各項經濟支持服務人次占全市提供遭逢特殊境遇家庭各項經濟支持服務人次之比率
90          %                             就讀國小之新移民子女人數占全市國小學生數比率
91        NaN                                                NaN
92          %                       就讀公私立國中之新移民子女人數占全市公私立國中學生數比率
93        NaN                                                NaN
94          %                3至未滿6歲新移民子女優先進入公立幼兒園人數占全市公立幼兒園人數之比率
95          %              0-3歲完成兒童發展篩檢表之新移民子女人數占本市0-3歲新移民子女人數比率
96          %          提供新移民子女發展遲緩者早期療育服務人數占全市提供發展遲緩者早期療育服務人數之比率
97          %  就讀私立幼兒園之2至6歲身心障礙幼兒且其父母一方為新移民者教育補助人數占全市私立幼兒園之2至...
98          %  本市國民小學依教育部「國民小學辦理兒童課後照顧服務人員及資格標準修正條文」及「臺北市國民小學...

                                           Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0                                                  公式     資料產生週期     資料產生時間
1                                                 NaN        NaN        NaN
2                             (全市新移民人口數/全市新移民人口數)×100          月       當期期末
3                             (大陸港澳配偶人數/全市新移民人口數)×100          月       當期期末
4                             (其他外籍配偶人數/全市新移民人口數)×100          月       當期期末
5                              (越南籍配偶人數/全市新移民人口數)×100          月       當期期末
6                              (日本籍配偶人數/全市新移民人口數)×100          月       當期期末
7                              (美國籍配偶人數/全市新移民人口數)×100          月       當期期末
8                              (印尼籍配偶人數/全市新移民人口數)×100          月       當期期末
9                              (韓國籍配偶人數/全市新移民人口數)×100          月       當期期末
10                            (加拿大籍配偶人數/全市新移民人口數)×100          月       當期期末
11                             (泰國籍配偶人數/全市新移民人口數)×100          月       當期期末
12                            (新加坡籍配偶人數/全市新移民人口數)×100          月       當期期末
13                            (菲律賓籍配偶人數/全市新移民人口數)×100          月       當期期末
14                             (緬甸籍配偶人數/全市新移民人口數)×100          月       當期期末
15                             (其他籍配偶人數/全市新移民人口數)×100          月       當期期末
16                            (新移民男性人口數÷新移民女性人口數)×100          月       當期期末
17                                 (新移民人口數/全市人口數)×100          月       當期期末
18                            (全市新移民人口數/全市新移民人口數)×100          月       當期期末
19                      (全市0至未滿6歲新移民人口數/全市新移民人口數)×100          月       當期期末
20                     (全市6至未滿12歲新移民人口數/全市新移民人口數)×100          月       當期期末
21                    (全市12至未滿15歲新移民人口數/全市新移民人口數)×100          月       當期期末
22                    (全市15至未滿18歲新移民人口數/全市新移民人口數)×100          月       當期期末
23                    (全市18至未滿24歲新移民人口數/全市新移民人口數)×100          月       當期期末
24                    (全市24至未滿30歲新移民人口數/全市新移民人口數)×100          月       當期期末
25                    (全市30至未滿45歲新移民人口數/全市新移民人口數)×100          月       當期期末
26                    (全市45至未滿65歲新移民人口數/全市新移民人口數)×100          月       當期期末
27                       (全市65歲以上新移民人口數/全市新移民人口數)×100          月       當期期末
28                        (全市年齡不詳新移民人口數/全市新移民人口數)×100          月       當期期末
29                            (全市新移民人口數/全市新移民人口數)×100          月       當期期末
..                                                ...        ...        ...
69            (新移民參加就業研習班及團體就業研習班人次/新移民參加各類課程總人次)×100          季         當期
70                          (新移民取得汽車駕照人數/期中新移民人數)×100          季         當期
71                   (新移民取得汽車或機車駕照人次/新移民參加駕照考試人次)×100          季         當期
72  (新移民各項諮詢服務人次/新移民各項諮詢服務總人次)×100\n新移民各項諮詢服務總人次=新...          季         當期
73                   (新移民會館電話諮詢服務人次/新移民各項諮詢服務總人次)×100          月         當期
74                (新移民課程諮詢及申訴專線服務人次/新移民各項諮詢服務總人次)×100          季         當期
75                 (新移民職業訓練電話諮詢服務人次/新移民各項諮詢服務總人次)×100          季         當期
76                 (新移民就業服務電話諮詢服務人次/新移民各項諮詢服務總人次)×100          季         當期
77                  (新移民健康諮詢站諮詢服務人次/新移民各項諮詢服務總人次)×100          季         當期
78      (新移民婦女暨家庭服務中心外語諮詢專線家庭諮詢服務人次/新移民各項諮詢服務總人次)×100          季         當期
79                     (新移民法律諮詢服務人次/新移民各項諮詢服務總人次)×100          月         當期
80     (新移民婦女暨家庭服務中心及家暴中心提供法律諮詢服務人次/新移民各項諮詢服務總人次)×100          季         當期
81                      (有效求職推介新移民就業人數/新移民登記求職人數)×100          月         當期
82              (新移民參加就業研習班及團體就業研習班人次/全市參加就業研習人次)×100          季         當期
83                           (新移民參加職訓人次/全市參加職訓人次)×100          季         當期
84                      (新移民新婚個案已完訪案數/新婚新移民應建卡案數)×100          季         當期
85                  (新移民子女收案訪視個案已完訪案數/新移民子女應建卡案數)×100          季         當期
86              (提供新移民懷孕婦女產前衛教諮詢服務個案數/新移民懷孕婦女個案數)×100          季         當期
87  (新移民接受緊急救援、庇護安置及心理諮商輔導人次/全市接受緊急救援、庇護安置及心理諮商輔導人...          季         當期
88                  (辦理新移民多元文化週活動國小學校校數/全市國小學校校數)×100        學年度         當期
89  (提供遭逢特殊境遇新移民家庭各項經濟支持服務人次/全市提供遭逢特殊境遇家庭各項經濟支持服務人...          季         當期
90                         (就讀國小之新移民子女人數/全市國小學生數)×100        學年度         當期
91                                                NaN        NaN        NaN
92                   (就讀公私立國中之新移民子女人數/全市公私立國中學生數)×100        學年度         當期
93                                                NaN        NaN        NaN
94             (新移民3至未滿6歲子女優先進入公立幼兒園人數/公立幼兒園核定人數)×100        學年度         當期
95          (0-3歲完成兒童發展篩檢表之新移民子女人數/全市0-3歲新移民子女人數)×100          季         當期
96       (提供新移民子女發展遲緩者早期療育服務人數/全市提供發展遲緩者早期療育服務人數)×100          季         當期
97  (新移民就讀私立幼兒園之2至6歲身心障礙幼兒教育補助人數/全市私立幼兒園之2至6歲身心障礙幼...        學年度         當期
98                   (新移民國小兒童課後輔導人次/全市國小兒童課後輔導人次)×100        學年度         當期

           Unnamed: 9                ...                       Unnamed: 48  \
0                  資料                ...                               NaN
1              94年(底)                ...                       106年1-9月(底)
2   100.00\n(27,645人)                ...                 100.00\n(34,853人)
3                90.1                ...                             89.05
4                 9.9                ...                             10.95
5                4.51                ...                              2.67
6                 NaN                ...                              1.69
7                 NaN                ...                              1.37
8                1.44                ...                               0.6
9                 NaN                ...                              0.47
10                NaN                ...                              0.36
11               0.62                ...                              0.37
12                NaN                ...                              0.28
13               0.39                ...                              0.26
14                  …                ...                              0.19
15               2.68                ...                              2.68
16                NaN                ...                             11.48
17               1.06                ...                               1.3
18                NaN                ...                 100.00\n(34,853人)
19                NaN                ...                                 0
20                NaN                ...                                 0
21                NaN                ...                              0.01
22                NaN                ...                              0.01
23                NaN                ...                              0.84
24                NaN                ...                             10.73
25                NaN                ...                             56.12
26                NaN                ...                             28.64
27                NaN                ...                              3.64
28                NaN                ...                              0.01
29                NaN                ...                 100.00\n(34,853人)
..                ...                ...                               ...
69              26.13                ...                             21.73
70               1.11                ...                              0.97
71                  …                ...                             63.61
72  100.00\n(3,272人次)                ...                 100.00\n(7,306人次)
73               2.96                ...                             30.19
74                  -                ...                              0.11
75                  …                ...                              1.04
76                  …                ...                             10.05
77                NaN                ...                             41.55
78              86.77                ...                              14.3
79               1.01                ...                              0.83
80               9.26                ...                              1.92
81              56.46                ...                             30.85
82              12.14                ...                              3.91
83               3.91                ...                              1.93
84                100                ...                               100
85                100                ...                               100
86                100                ...                               100
87               5.95                ...                              3.74
88                100                ...                                 …
89               1.21                ...                              1.42
90               2.69                ...                                 …
91                NaN                ...                        (新移民學生數:人)
92               1.09                ...                                 …
93                NaN                ...                        (新移民學生數:人)
94               2.91                ...                                 …
95                  …                ...                             72.13
96               3.94                ...                              5.21
97               3.02                ...                                 …
98               0.28                ...                                 …

          Unnamed: 49        Unnamed: 50        Unnamed: 51  \
0                 NaN                NaN                NaN
1             106年(底)        106年1-3月(底)        107年1-3月(底)
2   100.00\n(35,063人)  100.00\n(34,587人)  100.00\n(35,244人)
3               89.01               89.1              88.96
4               10.99               10.9              11.04
5                2.67               2.68               2.67
6                1.68               1.68                1.7
7                1.38               1.36                1.4
8                 0.6                0.6                0.6
9                0.48               0.47               0.48
10               0.37               0.37               0.37
11               0.39               0.36               0.39
12               0.28               0.28               0.28
13               0.27               0.27               0.27
14               0.19               0.19               0.18
15                2.7               2.65               2.69
16              11.59              11.48              11.71
17               1.31               1.28               1.31
18  100.00\n(35,063人)  100.00\n(34,587人)  100.00\n(35,244人)
19                  0                  0                  0
20                  0               0.01                  0
21                  0               0.01                  0
22               0.01               0.01               0.01
23               0.26               0.76               0.22
24               5.92              10.37               5.59
25              54.32              56.31              53.98
26              34.67              28.86              35.21
27               4.81               3.67               4.99
28               0.01               0.01               0.01

In [46]:
import pandas 
df=pd.read_csv('taipeifireworkpot.csv',encoding='big5')
df

     分隊名稱     X97      Y97
0    古亭分隊  304296  2767192
1    華山分隊  302552  2771114
2    忠孝分隊  303184  2770719
3    泉州分隊  301717  2768601
4    城中分隊  301807  2771076
5    雙園分隊  300004  2769060
6    龍山分隊  300137  2770145
7    萬芳分隊  307177  2766126
8    景美分隊  304631  2765034
9    木柵分隊  306876  2764656
10   寶橋分隊  306021  2763666
11   金華分隊  303258  2769481
12   安和分隊  305731  2769536
13   復興分隊  304827  2769217
14   南港分隊  311271  2771970
15   舊莊分隊  312085  2770911
16   信義分隊  307391  2770418
17   永吉分隊  307433  2770941
18   莊敬分隊  307040  2769197
19   成德分隊  309230  2771216
20   大直分隊  306136  2774777
21   松江分隊  303875  2771146
22   圓山分隊  303386  2773471
23   八德分隊  306804  2771272
24   中崙分隊  305076  2771247
25   東湖分隊  311835  2773391
26   大湖分隊  310690  2775204
27   內湖分隊  309559  2773607
28   民權分隊  308283  2773311
29   建國分隊  304063  2773398
30   建成分隊  302289  2771942
31   延平分隊  301597  2771439
32   大同分隊  301831  2772685
33  山仔后分隊  305021  2780715
34   天母分隊  303737  2779758
35   福安分隊  300166  2776454
36   社子分隊  301597  2774636
37   劍潭分隊  303168  2775854
38   雙溪分隊  304937  2776701
39  陽明山分隊  305111  2782678
40   光明分隊  300664  2780842
41   關渡分隊  297059  2779489
42   石牌分隊  302127  2778941
43   秀山分隊  299695  2781960
44   後港分隊  302255  2775551

In [47]:
import pandas 
df=pd.read_csv('FIFA.csv',encoding='big5')
df

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,Yes,89.0,Group Stage,No,0,NaN,NaN
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,90.0
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,3,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,1,0,0,No,4.0,Group Stage,No,0,NaN,NaN
7,15-06-2018,Spain,Portugal,3,61,12,5,5,2,5,...,1,0,0,Yes,24.0,Group Stage,No,0,NaN,NaN
8,16-06-2018,France,Australia,2,51,12,5,4,3,5,...,1,0,0,Yes,58.0,Group Stage,No,0,NaN,NaN
9,16-06-2018,Australia,France,1,49,4,1,2,1,1,...,3,0,0,No,62.0,Group Stage,No,0,1.0,81.0
10,16-06-2018,Argentina,Iceland,1,72,26,7,9,10,10,...,0,0,0,No,19.0,Group Stage,No,0,NaN,NaN
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN
12,16-06-2018,Peru,Denmark,0,52,18,6,7,5,3,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
13,16-06-2018,Denmark,Peru,1,48,10,3,5,2,7,...,2,0,0,Yes,59.0,Group Stage,No,0,NaN,NaN
14,17-06-2018,Croatia,Nigeria,2,54,11,2,7,2,6,...,2,0,0,Yes,32.0,Group Stage,No,0,NaN,NaN
15,17-06-2018,Nigeria,Croatia,0,46,14,2,5,7,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,32.0
16,17-06-2018,Costa Rica,Serbia,0,50,10,3,3,4,5,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
17,17-06-2018,Serbia,Costa Rica,1,50,10,3,5,2,4,...,2,0,0,Yes,56.0,Group Stage,No,0,NaN,NaN
18,17-06-2018,Germany,Mexico,0,60,25,9,9,7,8,...,2,0,0,Yes,NaN,Group Stage,No,0,NaN,NaN
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,2,0,0,No,35.0,Group Stage,No,0,NaN,NaN
20,17-06-2018,Brazil,Switzerland,1,52,20,4,9,7,7,...,1,0,0,Yes,20.0,Group Stage,No,0,NaN,NaN
21,17-06-2018,Switzerland,Brazil,1,48,6,2,4,0,2,...,3,0,0,No,50.0,Group Stage,No,0,NaN,NaN
22,18-06-2018,Sweden,Korea Republic,1,52,15,4,5,6,6,...,1,0,0,Yes,65.0,Group Stage,No,0,NaN,NaN
23,18-06-2018,Korea Republic,Sweden,0,48,5,0,2,3,5,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
24,18-06-2018,Belgium,Panama,3,61,15,6,7,2,9,...,3,0,0,Yes,47.0,Group Stage,No,0,NaN,NaN
25,18-06-2018,Panama,Belgium,0,39,6,2,4,0,3,...,5,0,0,No,NaN,Group Stage,No,0,NaN,NaN
26,18-06-2018,Tunisia,England,1,41,6,1,3,2,2,...,0,0,0,No,11.0,Group Stage,No,0,NaN,NaN
27,18-06-2018,England,Tunisia,2,59,17,7,7,3,7,...,1,0,0,Yes,35.0,Group Stage,No,0,NaN,NaN
28,19-06-2018,Colombia,Japan,1,41,8,3,1,4,3,...,2,0,1,No,39.0,Group Stage,No,0,NaN,NaN
29,19-06-2018,Japan,Colombia,2,59,14,6,5,3,6,...,1,0,0,Yes,6.0,Group Stage,No,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,30-06-2018,Uruguay,Portugal,2,39,6,3,2,1,2,...,0,0,0,Yes,7.0,Round of 16,No,0,NaN,NaN
99,30-06-2018,Portugal,Uruguay,1,61,20,5,1,8,10,...,1,0,0,No,55.0,Round of 16,No,0,NaN,NaN
100,01-07-2018,Spain,Russia,1,75,25,9,6,10,6,...,1,0,0,No,12.0,Round of 16,Yes,3,NaN,NaN
101,01-07-2018,Russia,Spain,1,25,6,1,3,2,5,...,2,0,0,Yes,41.0,Round of 16,Yes,4,1.0,12.0
102,01-07-2018,Croatia,Denmark,1,54,22,7,8,7,5,...,0,0,0,Yes,4.0,Round of 16,Yes,3,NaN,NaN
103,01-07-2018,Denmark,Croatia,1,46,15,3,10,2,4,...,1,0,0,No,1.0,Round of 16,Yes,2,NaN,NaN
104,02-07-2018,Brazil,Mexico,2,47,21,10,7,4,8,...,2,0,0,Yes,51.0,Round of 16,No,0,NaN,NaN
105,02-07-2018,Mexico,Brazil,0,53,13,1,4,8,7,...,4,0,0,No,NaN,Round of 16,No,0,NaN,NaN
106,02-07-2018,Belgium,Japan,3,56,24,8,10,6,10,...,0,0,0,Yes,69.0,Round of 16,No,0,NaN,NaN
107,02-07-2018,Japan,Belgium,2,44,11,4,4,3,6,...,1,0,0,No,48.0,Round of 16,No,0,NaN,NaN
108,03-07-2018,Sweden,Switzerland,1,37,12,3,6,3,3,...,1,0,0,Yes,66.0,Round of 16,No,0,NaN,NaN
109,03-07-2018,Switzerland,Sweden,0,63,18,4,5,9,11,...,2,0,1,No,NaN,Round of 16,No,0,NaN,NaN
110,03-07-2018,Colombia,England,1,48,14,4,7,3,2,...,6,0,0,No,90.0,Round of 16,Yes,3,NaN,NaN
111,03-07-2018,England,Colombia,1,51,16,2,9,5,7,...,2,0,0,Yes,57.0,Round of 16,Yes,4,NaN,NaN
112,06-07-2018,Uruguay,France,0,42,11,4,6,1,4,...,2,0,0,No,NaN,Quarter Finals,No,0,NaN,NaN
113,06-07-2018,France,Uruguay,2,58,11,2,7,2,3,...,2,0,0,Yes,40.0,Quarter Finals,No,0,NaN,NaN
114,06-07-2018,Brazil,Belgium,1,57,26,9,7,10,8,...,2,0,0,No,NaN,Quarter Finals,No,0,1.0,13.0
115,06-07-2018,Belgium,Brazil,2,43,8,3,3,2,4,...,2,0,0,Yes,13.0,Quarter Finals,No,0,NaN,NaN
116,07-07-2018,Sweden,England,0,43,7,3,3,1,1,...,2,0,0,No,NaN,Quarter Finals,No,0,NaN,NaN
117,07-07-2018,England,Sweden,2,57,12,2,4,6,6,...,1,0,0,Yes,30.0,Quarter Finals,No,0,NaN,NaN
118,07-07-2018,Russia,Croatia,2,38,13,7,4,2,6,...,1,0,0,No,31.0,Quarter Finals,Yes,3,NaN,NaN
119,07-07-2018,Croatia,Russia,2,62,17,3,10,4,8,...,4,0,0,Yes,39.0,Quarter Finals,Yes,4,NaN,NaN
120,10-07-2018,France,Belgium,1,40,19,5,8,6,4,...,2,0,0,Yes,51.0,Semi- Finals,No,0,NaN,NaN
121,10-07-2018,Belgium,France,0,60,9,3,5,1,5,...,3,0,0,No,NaN,Semi- Finals,No,0,NaN,NaN
122,11-07-2018,Croatia,England,2,54,22,7,11,4,8,...,2,0,0,Yes,68.0,Semi- Finals,No,0,NaN,NaN
123,11-07-2018,England,Croatia,1,46,11,1,6,4,4,...,1,0,0,No,5.0,Semi- Finals,No,0,NaN,NaN
124,14-07-2018,Belgium,England,2,43,12,4,3,5,4,...,1,0,0,Yes,4.0,3rd Place,No,0,NaN,NaN
125,14-07-2018,England,Belgium,0,57,15,5,7,3,5,...,2,0,0,No,NaN,3rd Place,No,0,NaN,NaN
126,15-07-2018,France,Croatia,4,39,8,6,1,1,2,...,2,0,0,Yes,18.0,Final,No,0,1.0,18.0
127,15-07-2018,Croatia,France,2,61,15,3,8,4,6,...,1,0,0,No,28.0,Final,No,0,NaN,NaN

In [48]:
dfbew=df[df['Ball Possession %'],41]

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [49]:
dfbew=df[df['Ball Possession %']<41]

In [50]:
dfbew.head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,3,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,1,0,0,No,4.0,Group Stage,No,0,NaN,NaN
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,2,0,0,No,35.0,Group Stage,No,0,NaN,NaN

In [51]:
dfbew['item']=0

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [52]:
dfbew=df[df['Ball Possession %	'].between(41,48)]

KeyError: 'Ball Possession %\t'

In [53]:
dfbew1=df[df['Ball Possession %'].between(41,48)]

In [54]:
dfbew1['item']=1

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [55]:
dfbew=df[df['Ball Possession %']<42]

In [56]:
dfbew

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,3,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,1,0,0,No,4.0,Group Stage,No,0,NaN,NaN
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,2,0,0,No,35.0,Group Stage,No,0,NaN,NaN
25,18-06-2018,Panama,Belgium,0,39,6,2,4,0,3,...,5,0,0,No,NaN,Group Stage,No,0,NaN,NaN
26,18-06-2018,Tunisia,England,1,41,6,1,3,2,2,...,0,0,0,No,11.0,Group Stage,No,0,NaN,NaN
28,19-06-2018,Colombia,Japan,1,41,8,3,1,4,3,...,2,0,1,No,39.0,Group Stage,No,0,NaN,NaN
38,20-06-2018,Iran,Spain,0,30,5,0,5,0,2,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
47,22-06-2018,Costa Rica,Brazil,0,34,4,0,4,0,1,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
54,23-06-2018,Korea Republic,Mexico,1,41,17,6,2,9,7,...,4,0,0,No,90.0,Group Stage,No,0,NaN,NaN
57,23-06-2018,Sweden,Germany,1,29,8,6,1,1,3,...,2,0,0,No,32.0,Group Stage,No,0,NaN,NaN
67,25-06-2018,Egypt,Saudi Arabia,1,39,8,1,6,1,2,...,2,0,0,Yes,22.0,Group Stage,No,0,NaN,NaN
69,25-06-2018,Morocco,Spain,2,32,6,3,2,1,1,...,6,0,0,No,14.0,Group Stage,No,0,NaN,NaN
70,25-06-2018,Iran,Portugal,1,32,8,2,5,1,1,...,2,0,0,No,90.0,Group Stage,No,0,NaN,NaN
72,26-06-2018,Denmark,France,0,38,5,1,2,2,4,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
76,26-06-2018,Nigeria,Argentina,1,34,9,3,5,1,3,...,2,0,0,No,51.0,Group Stage,No,0,NaN,NaN
78,26-06-2018,Iceland,Croatia,1,41,17,6,8,3,10,...,3,0,0,Yes,76.0,Group Stage,No,0,NaN,NaN
80,27-06-2018,Korea Republic,Germany,2,30,11,5,5,1,3,...,4,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN
83,27-06-2018,Sweden,Mexico,3,35,13,5,7,1,3,...,2,0,0,Yes,50.0,Group Stage,No,0,NaN,NaN
87,27-06-2018,Costa Rica,Switzerland,2,40,14,6,6,2,5,...,3,0,0,No,56.0,Group Stage,No,0,NaN,NaN
92,28-06-2018,Panama,Tunisia,1,36,9,4,4,1,0,...,3,0,0,No,33.0,Group Stage,No,0,NaN,NaN
96,30-06-2018,France,Argentina,4,41,9,4,4,1,0,...,3,0,0,Yes,13.0,Round of 16,No,0,NaN,NaN
98,30-06-2018,Uruguay,Portugal,2,39,6,3,2,1,2,...,0,0,0,Yes,7.0,Round of 16,No,0,NaN,NaN
101,01-07-2018,Russia,Spain,1,25,6,1,3,2,5,...,2,0,0,Yes,41.0,Round of 16,Yes,4,1.0,12.0
108,03-07-2018,Sweden,Switzerland,1,37,12,3,6,3,3,...,1,0,0,Yes,66.0,Round of 16,No,0,NaN,NaN
118,07-07-2018,Russia,Croatia,2,38,13,7,4,2,6,...,1,0,0,No,31.0,Quarter Finals,Yes,3,NaN,NaN
120,10-07-2018,France,Belgium,1,40,19,5,8,6,4,...,2,0,0,Yes,51.0,Semi- Finals,No,0,NaN,NaN
126,15-07-2018,France,Croatia,4,39,8,6,1,1,2,...,2,0,0,Yes,18.0,Final,No,0,1.0,18.0

In [58]:
dfbew['item']=0

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [59]:
dfbew1=df[df['Ball Possession %'].between(42,48)]

In [60]:
dfbew1

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
13,16-06-2018,Denmark,Peru,1,48,10,3,5,2,7,...,2,0,0,Yes,59.0,Group Stage,No,0,NaN,NaN
15,17-06-2018,Nigeria,Croatia,0,46,14,2,5,7,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,32.0
21,17-06-2018,Switzerland,Brazil,1,48,6,2,4,0,2,...,3,0,0,No,50.0,Group Stage,No,0,NaN,NaN
23,18-06-2018,Korea Republic,Sweden,0,48,5,0,2,3,5,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
31,19-06-2018,Senegal,Poland,2,43,8,2,4,2,3,...,2,0,0,Yes,60.0,Group Stage,No,0,NaN,NaN
32,19-06-2018,Russia,Egypt,3,47,11,3,5,3,7,...,1,0,0,Yes,59.0,Group Stage,No,0,NaN,NaN
34,20-06-2018,Portugal,Morocco,1,47,10,2,4,4,5,...,1,0,0,Yes,4.0,Group Stage,No,0,NaN,NaN
36,20-06-2018,Uruguay,Saudi Arabia,1,47,13,4,6,3,3,...,0,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN
42,21-06-2018,France,Peru,1,44,12,4,6,2,5,...,2,0,0,Yes,34.0,Group Stage,No,0,NaN,NaN
45,21-06-2018,Croatia,Argentina,3,42,15,5,6,4,2,...,4,0,0,Yes,53.0,Group Stage,No,0,NaN,NaN
49,22-06-2018,Iceland,Nigeria,0,42,10,3,6,1,5,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
50,22-06-2018,Serbia,Switzerland,1,42,12,3,7,2,3,...,4,0,0,No,5.0,Group Stage,No,0,NaN,NaN
53,23-06-2018,Tunisia,Belgium,2,48,15,5,6,4,2,...,1,0,0,No,18.0,Group Stage,No,0,NaN,NaN
59,24-06-2018,Panama,England,1,42,8,2,5,1,2,...,3,0,0,No,78.0,Group Stage,No,0,NaN,NaN
61,24-06-2018,Senegal,Japan,2,46,14,7,5,2,5,...,3,0,0,Yes,11.0,Group Stage,No,0,NaN,NaN
62,24-06-2018,Poland,Colombia,0,45,9,2,3,4,7,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
65,25-06-2018,Russia,Uruguay,0,44,3,1,1,1,2,...,1,1,0,No,NaN,Group Stage,No,0,1.0,23.0
75,26-06-2018,Peru,Australia,2,47,4,3,1,0,3,...,2,0,0,Yes,18.0,Group Stage,No,0,NaN,NaN
84,27-06-2018,Serbia,Brazil,0,44,10,1,5,4,5,...,3,0,0,No,NaN,Group Stage,No,0,NaN,NaN
89,28-06-2018,Poland,Japan,1,46,11,2,5,4,7,...,0,0,0,Yes,59.0,Group Stage,No,0,NaN,NaN
90,28-06-2018,Senegal,Colombia,0,43,8,3,4,1,1,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
94,28-06-2018,England,Belgium,0,48,13,1,7,5,7,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
103,01-07-2018,Denmark,Croatia,1,46,15,3,10,2,4,...,1,0,0,No,1.0,Round of 16,Yes,2,NaN,NaN
104,02-07-2018,Brazil,Mexico,2,47,21,10,7,4,8,...,2,0,0,Yes,51.0,Round of 16,No,0,NaN,NaN
107,02-07-2018,Japan,Belgium,2,44,11,4,4,3,6,...,1,0,0,No,48.0,Round of 16,No,0,NaN,NaN
110,03-07-2018,Colombia,England,1,48,14,4,7,3,2,...,6,0,0,No,90.0,Round of 16,Yes,3,NaN,NaN
112,06-07-2018,Uruguay,France,0,42,11,4,6,1,4,...,2,0,0,No,NaN,Quarter Finals,No,0,NaN,NaN
115,06-07-2018,Belgium,Brazil,2,43,8,3,3,2,4,...,2,0,0,Yes,13.0,Quarter Finals,No,0,NaN,NaN
116,07-07-2018,Sweden,England,0,43,7,3,3,1,1,...,2,0,0,No,NaN,Quarter Finals,No,0,NaN,NaN
123,11-07-2018,England,Croatia,1,46,11,1,6,4,4,...,1,0,0,No,5.0,Semi- Finals,No,0,NaN,NaN
124,14-07-2018,Belgium,England,2,43,12,4,3,5,4,...,1,0,0,Yes,4.0,3rd Place,No,0,NaN,NaN

In [61]:
dfbew1['item']=1

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [62]:
dfbew2=df[df['Ball Possession %'].between(49,57)]

In [63]:
dfbew2

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,Yes,89.0,Group Stage,No,0,NaN,NaN
8,16-06-2018,France,Australia,2,51,12,5,4,3,5,...,1,0,0,Yes,58.0,Group Stage,No,0,NaN,NaN
9,16-06-2018,Australia,France,1,49,4,1,2,1,1,...,3,0,0,No,62.0,Group Stage,No,0,1.0,81.0
12,16-06-2018,Peru,Denmark,0,52,18,6,7,5,3,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
14,17-06-2018,Croatia,Nigeria,2,54,11,2,7,2,6,...,2,0,0,Yes,32.0,Group Stage,No,0,NaN,NaN
16,17-06-2018,Costa Rica,Serbia,0,50,10,3,3,4,5,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
17,17-06-2018,Serbia,Costa Rica,1,50,10,3,5,2,4,...,2,0,0,Yes,56.0,Group Stage,No,0,NaN,NaN
20,17-06-2018,Brazil,Switzerland,1,52,20,4,9,7,7,...,1,0,0,Yes,20.0,Group Stage,No,0,NaN,NaN
22,18-06-2018,Sweden,Korea Republic,1,52,15,4,5,6,6,...,1,0,0,Yes,65.0,Group Stage,No,0,NaN,NaN
30,19-06-2018,Poland,Senegal,1,57,10,4,5,1,3,...,1,0,0,No,37.0,Group Stage,No,0,1.0,37.0
33,19-06-2018,Egypt,Russia,1,53,13,1,8,4,4,...,1,0,0,No,47.0,Group Stage,No,0,1.0,47.0
35,20-06-2018,Morocco,Portugal,0,53,16,4,10,2,7,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
37,20-06-2018,Saudi Arabia,Uruguay,0,53,8,3,3,2,4,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
40,21-06-2018,Denmark,Australia,1,49,10,5,5,0,3,...,2,0,0,Yes,7.0,Group Stage,No,0,NaN,NaN
41,21-06-2018,Australia,Denmark,1,51,14,5,5,4,5,...,0,0,0,No,38.0,Group Stage,No,0,NaN,NaN
43,21-06-2018,Peru,France,0,56,10,2,6,2,3,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
52,23-06-2018,Belgium,Tunisia,5,52,23,12,8,3,5,...,0,0,0,Yes,6.0,Group Stage,No,0,NaN,NaN
60,24-06-2018,Japan,Senegal,2,54,7,3,2,2,2,...,2,0,0,No,34.0,Group Stage,No,0,NaN,NaN
63,24-06-2018,Colombia,Poland,3,55,13,3,5,5,5,...,0,0,0,Yes,40.0,Group Stage,No,0,NaN,NaN
64,25-06-2018,Uruguay,Russia,3,56,17,7,6,4,4,...,1,0,0,Yes,10.0,Group Stage,No,0,NaN,NaN
74,26-06-2018,Australia,Peru,0,53,14,2,7,5,8,...,4,0,0,No,NaN,Group Stage,No,0,NaN,NaN
85,27-06-2018,Brazil,Serbia,2,56,13,6,3,4,9,...,0,0,0,Yes,36.0,Group Stage,No,0,NaN,NaN
88,28-06-2018,Japan,Poland,0,54,10,3,4,3,5,...,1,0,0,No,NaN,Group Stage,No,0,NaN,NaN
91,28-06-2018,Colombia,Senegal,1,57,4,2,1,1,3,...,1,0,0,Yes,74.0,Group Stage,No,0,NaN,NaN
95,28-06-2018,Belgium,England,1,52,15,4,4,7,2,...,2,0,0,Yes,51.0,Group Stage,No,0,NaN,NaN
102,01-07-2018,Croatia,Denmark,1,54,22,7,8,7,5,...,0,0,0,Yes,4.0,Round of 16,Yes,3,NaN,NaN
105,02-07-2018,Mexico,Brazil,0,53,13,1,4,8,7,...,4,0,0,No,NaN,Round of 16,No,0,NaN,NaN
106,02-07-2018,Belgium,Japan,3,56,24,8,10,6,10,...,0,0,0,Yes,69.0,Round of 16,No,0,NaN,NaN
111,03-07-2018,England,Colombia,1,51,16,2,9,5,7,...,2,0,0,Yes,57.0,Round of 16,Yes,4,NaN,NaN
114,06-07-2018,Brazil,Belgium,1,57,26,9,7,10,8,...,2,0,0,No,NaN,Quarter Finals,No,0,1.0,13.0
117,07-07-2018,England,Sweden,2,57,12,2,4,6,6,...,1,0,0,Yes,30.0,Quarter Finals,No,0,NaN,NaN
122,11-07-2018,Croatia,England,2,54,22,7,11,4,8,...,2,0,0,Yes,68.0,Semi- Finals,No,0,NaN,NaN
125,14-07-2018,England,Belgium,0,57,15,5,7,3,5,...,2,0,0,No,NaN,3rd Place,No,0,NaN,NaN

In [64]:
dfbew2['item']=2

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [65]:
dfbew3=df[df['Ball Possession %']>57]

In [66]:
dfbew3

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,90.0
7,15-06-2018,Spain,Portugal,3,61,12,5,5,2,5,...,1,0,0,Yes,24.0,Group Stage,No,0,NaN,NaN
10,16-06-2018,Argentina,Iceland,1,72,26,7,9,10,10,...,0,0,0,No,19.0,Group Stage,No,0,NaN,NaN
18,17-06-2018,Germany,Mexico,0,60,25,9,9,7,8,...,2,0,0,Yes,NaN,Group Stage,No,0,NaN,NaN
24,18-06-2018,Belgium,Panama,3,61,15,6,7,2,9,...,3,0,0,Yes,47.0,Group Stage,No,0,NaN,NaN
27,18-06-2018,England,Tunisia,2,59,17,7,7,3,7,...,1,0,0,Yes,35.0,Group Stage,No,0,NaN,NaN
29,19-06-2018,Japan,Colombia,2,59,14,6,5,3,6,...,1,0,0,Yes,6.0,Group Stage,No,0,NaN,NaN
39,20-06-2018,Spain,Iran,1,70,17,3,6,8,6,...,0,0,0,Yes,54.0,Group Stage,No,0,NaN,NaN
44,21-06-2018,Argentina,Croatia,0,58,10,3,3,4,5,...,3,0,0,No,NaN,Group Stage,No,0,NaN,NaN
46,22-06-2018,Brazil,Costa Rica,2,66,23,9,9,5,10,...,2,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN
48,22-06-2018,Nigeria,Iceland,2,58,16,4,6,6,6,...,1,0,0,Yes,49.0,Group Stage,No,0,NaN,NaN
51,22-06-2018,Switzerland,Serbia,2,58,20,5,8,7,7,...,1,0,0,Yes,52.0,Group Stage,No,0,NaN,NaN
55,23-06-2018,Mexico,Korea Republic,2,59,13,5,6,2,5,...,0,0,0,Yes,26.0,Group Stage,No,0,NaN,NaN
56,23-06-2018,Germany,Sweden,2,71,16,5,4,7,8,...,0,1,0,Yes,48.0,Group Stage,No,0,NaN,NaN
58,24-06-2018,England,Panama,6,58,12,7,3,2,3,...,1,0,0,Yes,8.0,Group Stage,No,0,NaN,NaN
66,25-06-2018,Saudi Arabia,Egypt,2,61,22,7,10,5,7,...,0,0,0,No,45.0,Group Stage,No,0,NaN,NaN
68,25-06-2018,Spain,Morocco,2,68,16,4,11,1,7,...,0,0,0,Yes,19.0,Group Stage,No,0,NaN,NaN
71,25-06-2018,Portugal,Iran,1,68,14,4,7,3,5,...,4,0,0,Yes,45.0,Group Stage,No,0,NaN,NaN
73,26-06-2018,France,Denmark,0,62,11,4,6,1,2,...,0,0,0,Yes,NaN,Group Stage,No,0,NaN,NaN
77,26-06-2018,Argentina,Nigeria,2,66,8,4,3,1,5,...,3,0,0,Yes,14.0,Group Stage,No,0,NaN,NaN
79,26-06-2018,Croatia,Iceland,2,59,13,2,8,3,5,...,2,0,0,No,53.0,Group Stage,No,0,NaN,NaN
81,27-06-2018,Germany,Korea Republic,0,70,26,6,11,9,9,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
82,27-06-2018,Mexico,Sweden,0,65,19,3,8,8,7,...,3,0,0,No,NaN,Group Stage,No,0,1.0,74.0
86,27-06-2018,Switzerland,Costa Rica,2,60,12,3,5,4,6,...,3,0,0,Yes,31.0,Group Stage,No,0,1.0,90.0
93,28-06-2018,Tunisia,Panama,2,64,15,7,4,4,6,...,3,0,0,Yes,51.0,Group Stage,No,0,1.0,33.0
97,30-06-2018,Argentina,France,3,59,9,4,1,4,4,...,5,0,0,No,41.0,Round of 16,No,0,NaN,NaN
99,30-06-2018,Portugal,Uruguay,1,61,20,5,1,8,10,...,1,0,0,No,55.0,Round of 16,No,0,NaN,NaN
100,01-07-2018,Spain,Russia,1,75,25,9,6,10,6,...,1,0,0,No,12.0,Round of 16,Yes,3,NaN,NaN
109,03-07-2018,Switzerland,Sweden,0,63,18,4,5,9,11,...,2,0,1,No,NaN,Round of 16,No,0,NaN,NaN
113,06-07-2018,France,Uruguay,2,58,11,2,7,2,3,...,2,0,0,Yes,40.0,Quarter Finals,No,0,NaN,NaN
119,07-07-2018,Croatia,Russia,2,62,17,3,10,4,8,...,4,0,0,Yes,39.0,Quarter Finals,Yes,4,NaN,NaN
121,10-07-2018,Belgium,France,0,60,9,3,5,1,5,...,3,0,0,No,NaN,Semi- Finals,No,0,NaN,NaN
127,15-07-2018,Croatia,France,2,61,15,3,8,4,6,...,1,0,0,No,28.0,Final,No,0,NaN,NaN

In [67]:
dfbew3['item']=3

C:\Users\EELab507\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [68]:
new=pd.concat([dfbew,dfbew1,dfbew2,dfbew3])

In [69]:
new.head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time,item
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN,0
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN,0
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,0,0,No,4.0,Group Stage,No,0,NaN,NaN,0
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN,0
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,0,0,No,35.0,Group Stage,No,0,NaN,NaN,0

In [70]:
new

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time,item
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN,0
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN,0
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,0,0,No,4.0,Group Stage,No,0,NaN,NaN,0
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,Yes,23.0,Group Stage,No,0,NaN,NaN,0
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,0,0,No,35.0,Group Stage,No,0,NaN,NaN,0
25,18-06-2018,Panama,Belgium,0,39,6,2,4,0,3,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,0
26,18-06-2018,Tunisia,England,1,41,6,1,3,2,2,...,0,0,No,11.0,Group Stage,No,0,NaN,NaN,0
28,19-06-2018,Colombia,Japan,1,41,8,3,1,4,3,...,0,1,No,39.0,Group Stage,No,0,NaN,NaN,0
38,20-06-2018,Iran,Spain,0,30,5,0,5,0,2,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,0
47,22-06-2018,Costa Rica,Brazil,0,34,4,0,4,0,1,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,0
54,23-06-2018,Korea Republic,Mexico,1,41,17,6,2,9,7,...,0,0,No,90.0,Group Stage,No,0,NaN,NaN,0
57,23-06-2018,Sweden,Germany,1,29,8,6,1,1,3,...,0,0,No,32.0,Group Stage,No,0,NaN,NaN,0
67,25-06-2018,Egypt,Saudi Arabia,1,39,8,1,6,1,2,...,0,0,Yes,22.0,Group Stage,No,0,NaN,NaN,0
69,25-06-2018,Morocco,Spain,2,32,6,3,2,1,1,...,0,0,No,14.0,Group Stage,No,0,NaN,NaN,0
70,25-06-2018,Iran,Portugal,1,32,8,2,5,1,1,...,0,0,No,90.0,Group Stage,No,0,NaN,NaN,0
72,26-06-2018,Denmark,France,0,38,5,1,2,2,4,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,0
76,26-06-2018,Nigeria,Argentina,1,34,9,3,5,1,3,...,0,0,No,51.0,Group Stage,No,0,NaN,NaN,0
78,26-06-2018,Iceland,Croatia,1,41,17,6,8,3,10,...,0,0,Yes,76.0,Group Stage,No,0,NaN,NaN,0
80,27-06-2018,Korea Republic,Germany,2,30,11,5,5,1,3,...,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN,0
83,27-06-2018,Sweden,Mexico,3,35,13,5,7,1,3,...,0,0,Yes,50.0,Group Stage,No,0,NaN,NaN,0
87,27-06-2018,Costa Rica,Switzerland,2,40,14,6,6,2,5,...,0,0,No,56.0,Group Stage,No,0,NaN,NaN,0
92,28-06-2018,Panama,Tunisia,1,36,9,4,4,1,0,...,0,0,No,33.0,Group Stage,No,0,NaN,NaN,0
96,30-06-2018,France,Argentina,4,41,9,4,4,1,0,...,0,0,Yes,13.0,Round of 16,No,0,NaN,NaN,0
98,30-06-2018,Uruguay,Portugal,2,39,6,3,2,1,2,...,0,0,Yes,7.0,Round of 16,No,0,NaN,NaN,0
101,01-07-2018,Russia,Spain,1,25,6,1,3,2,5,...,0,0,Yes,41.0,Round of 16,Yes,4,1.0,12.0,0
108,03-07-2018,Sweden,Switzerland,1,37,12,3,6,3,3,...,0,0,Yes,66.0,Round of 16,No,0,NaN,NaN,0
118,07-07-2018,Russia,Croatia,2,38,13,7,4,2,6,...,0,0,No,31.0,Quarter Finals,Yes,3,NaN,NaN,0
120,10-07-2018,France,Belgium,1,40,19,5,8,6,4,...,0,0,Yes,51.0,Semi- Finals,No,0,NaN,NaN,0
126,15-07-2018,France,Croatia,4,39,8,6,1,1,2,...,0,0,Yes,18.0,Final,No,0,1.0,18.0,0
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,17-06-2018,Germany,Mexico,0,60,25,9,9,7,8,...,0,0,Yes,NaN,Group Stage,No,0,NaN,NaN,3
24,18-06-2018,Belgium,Panama,3,61,15,6,7,2,9,...,0,0,Yes,47.0,Group Stage,No,0,NaN,NaN,3
27,18-06-2018,England,Tunisia,2,59,17,7,7,3,7,...,0,0,Yes,35.0,Group Stage,No,0,NaN,NaN,3
29,19-06-2018,Japan,Colombia,2,59,14,6,5,3,6,...,0,0,Yes,6.0,Group Stage,No,0,NaN,NaN,3
39,20-06-2018,Spain,Iran,1,70,17,3,6,8,6,...,0,0,Yes,54.0,Group Stage,No,0,NaN,NaN,3
44,21-06-2018,Argentina,Croatia,0,58,10,3,3,4,5,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,3
46,22-06-2018,Brazil,Costa Rica,2,66,23,9,9,5,10,...,0,0,Yes,90.0,Group Stage,No,0,NaN,NaN,3
48,22-06-2018,Nigeria,Iceland,2,58,16,4,6,6,6,...,0,0,Yes,49.0,Group Stage,No,0,NaN,NaN,3
51,22-06-2018,Switzerland,Serbia,2,58,20,5,8,7,7,...,0,0,Yes,52.0,Group Stage,No,0,NaN,NaN,3
55,23-06-2018,Mexico,Korea Republic,2,59,13,5,6,2,5,...,0,0,Yes,26.0,Group Stage,No,0,NaN,NaN,3
56,23-06-2018,Germany,Sweden,2,71,16,5,4,7,8,...,1,0,Yes,48.0,Group Stage,No,0,NaN,NaN,3
58,24-06-2018,England,Panama,6,58,12,7,3,2,3,...,0,0,Yes,8.0,Group Stage,No,0,NaN,NaN,3
66,25-06-2018,Saudi Arabia,Egypt,2,61,22,7,10,5,7,...,0,0,No,45.0,Group Stage,No,0,NaN,NaN,3
68,25-06-2018,Spain,Morocco,2,68,16,4,11,1,7,...,0,0,Yes,19.0,Group Stage,No,0,NaN,NaN,3
71,25-06-2018,Portugal,Iran,1,68,14,4,7,3,5,...,0,0,Yes,45.0,Group Stage,No,0,NaN,NaN,3
73,26-06-2018,France,Denmark,0,62,11,4,6,1,2,...,0,0,Yes,NaN,Group Stage,No,0,NaN,NaN,3
77,26-06-2018,Argentina,Nigeria,2,66,8,4,3,1,5,...,0,0,Yes,14.0,Group Stage,No,0,NaN,NaN,3
79,26-06-2018,Croatia,Iceland,2,59,13,2,8,3,5,...,0,0,No,53.0,Group Stage,No,0,NaN,NaN,3
81,27-06-2018,Germany,Korea Republic,0,70,26,6,11,9,9,...,0,0,No,NaN,Group Stage,No,0,NaN,NaN,3
82,27-06-2018,Mexico,Sweden,0,65,19,3,8,8,7,...,0,0,No,NaN,Group Stage,No,0,1.0,74.0,3
86,27-06-2018,Switzerland,Costa Rica,2,60,12,3,5,4,6,...,0,0,Yes,31.0,Group Stage,No,0,1.0,90.0,3
93,28-06-2018,Tunisia,Panama,2,64,15,7,4,4,6,...,0,0,Yes,51.0,Group Stage,No,0,1.0,33.0,3
97,30-06-2018,Argentina,France,3,59,9,4,1,4,4,...,0,0,No,41.0,Round of 16,No,0,NaN,NaN,3
99,30-06-2018,Portugal,Uruguay,1,61,20,5,1,8,10,...,0,0,No,55.0,Round of 16,No,0,NaN,NaN,3
100,01-07-2018,Spain,Russia,1,75,25,9,6,10,6,...,0,0,No,12.0,Round of 16,Yes,3,NaN,NaN,3
109,03-07-2018,Switzerland,Sweden,0,63,18,4,5,9,11,...,0,1,No,NaN,Round of 16,No,0,NaN,NaN,3
113,06-07-2018,France,Uruguay,2,58,11,2,7,2,3,...,0,0,Yes,40.0,Quarter Finals,No,0,NaN,NaN,3
119,07-07-2018,Croatia,Russia,2,62,17,3,10,4,8,...,0,0,Yes,39.0,Quarter Finals,Yes,4,NaN,NaN,3
121,10-07-2018,Belgium,France,0,60,9,3,5,1,5,...,0,0,No,NaN,Semi- Finals,No,0,NaN,NaN,3
127,15-07-2018,Croatia,France,2,61,15,3,8,4,6,...,0,0,No,28.0,Final,No,0,NaN,NaN,3

In [71]:
dfdata = new.groupby(by='item')['Goal Scored'].sum().to_frame()

In [72]:
dfdata

      Goal Scored
item
0              44
1              33
2              40
3              52